### ISSUE TITLE
Helper note:  may need to code sign dylib dependencies if in macOS app

### ISSUE THREAD

**Issue by sstadelman** [SwiftDocOrg/GraphViz#14]
A cairn for anyone else using in macOS app on Big Sur, with graphviz installed via `brew`: you may encounter code signing warnings, and an error that dependencies of pango cannot be loaded.  (`"it could load, so perhaps one of its dependents was not.  Try ldd."`).

A solution appears to be to manually sign the dependencies.  Probably do a better job of scoping to just the affected dirs, than this, but this pair should get you there: 
 
```sh
codesign -f -s "Apple Development: MyName (MyTeam)" /usr/local/opt/*/lib/*.dylib
codesign -f -s "Apple Development: MyName (MyTeam)" /usr/local/Cellar/*/*/lib/*.dylib
```

**Comment by mattt** [comment]
Thanks so much for sharing this important details, @sstadelman. I just merged #19, which updates the README with this information.
