### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by mattt** [SwiftDocOrg/GraphViz#21]
Tracking the GraphViz-specific work for https://github.com/SwiftDocOrg/swift-doc/issues/254

**Comment by mattt** [comment]
@compnerd Regarding your upstream [fix for the `gvToolTred` export](https://gitlab.com/graphviz/graphviz/-/merge_requests/1925), could we instead conditionally compile or simply remove support for `tred` on Windows? This is a recent addition to this library, and isn't essential to running `swift-doc`.

**Comment by compnerd** [comment]
I will have to try to see if I can figure out where the reference is arising from, but, yes, if we can remove the references to it, that would work.

**Comment by compnerd** [comment]
Seems like `removeEdgesImpliedByTransitivity` causes it.  If you think that removing it is a better solution, that might be a solution.

**Comment by compnerd** [comment]
At this point, we just need a new tag and we should be good for initial usage.

**Comment by mattt** [comment]
This is fixed as of #24.

Windows support is available with version 0.4.1.
