### ISSUE TITLE
Only for macOS?

### ISSUE THREAD

**Issue by kwccoin** [SwiftDocOrg/GraphViz#26]
Not iOS or no text file in and graphic file out?

**Comment by mattt** [comment]
I wrote this primarily for https://github.com/SwiftDocOrg/swift-doc, and haven't had an occasion to try it on iOS. https://github.com/SwiftDocOrg/GraphViz/issues/14 discusses use of this library for a macOS app, so I'd expect that the process would be similar for iOS.

On macOS, you can render a text file to an image using the GraphViz executables (like `dot`) directly.
